### ISSUE TITLE
请求时，出现参数重复的情况

### ISSUE THREAD

**Issue by AventusKent** [fatcherjs/fatcher#112]
<img width="471" alt="image" src="https://user-images.githubusercontent.com/73089757/166856672-f551da26-be93-4a40-80a7-7e0a28d699a7.png">

情况如下：
1.POST请求
2.content-type: application/x-www-form-urlencoded

出现情况：
请求失败，参数重复

**Comment by fanhaoyuan** [comment]
这个问题是自定义`Middlewares`中`payload`在使用后调用`next`没有置空，导致后续自动转换再次消费`payload`。

所以在调用`next`时将`payload`设置为`null`
